name: Build and publish the Drogon image

'on':
  push:
    tags:
      - '*'
    branches:
      - 'dev-0.1.0'

jobs:
  build-drogon-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Drogon version
        id: repository
        run: echo  "::set-output name=tag::$(cat package.json|grep '"version'|cut -d '"' -f4)"

      - name: Log in to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}}

      - name: Build & push container to docker hub
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./dockerfiles/Dockerfile.alpine
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/drogon:${{ steps.repository.outputs.tag }}
          
