name: Build and publish the Drogon image

'on':
  push:
    tags:
      - '*'
    branches:
      - 'dev-0.1.0'

jobs:
  build-drogon-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Drogon version
        id: repository
        run: echo  "::set-output name=tag::$(cat package.json|grep '"version'|cut -d '"' -f4)"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Drogon
        uses: docker/build-push-action@v3
        with:
          push: false
          context: .
          file: ./dockerfiles/Dockerfile.alpine
          tags: drogon:${{ steps.repository.outputs.tag }}

      - name: Push Drogon to ghcr
        run: docker tag drogon:${{ steps.repository.outputs.tag }} ghcr.io/${{ github.actor }}/drogon:${{ steps.repository.outputs.tag }}