name: Build and publish the gochain image

'on':
  push:
    tags:
      - '*'
    branches:
      - 'dev-0.1.0'

jobs:
  build-goloop-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: goloop version
        id: repository
        run: echo  "::set-output name=tag::$(curl -s https://api.github.com/repos/icon-project/goloop/releases/latest|grep '"name"'|cut -d '"' -f4)"

      - name: Clone goloop repository
        uses: actions/checkout@v2
        with:
          repository: icon-project/goloop
          ref: ${{ steps.repository.outputs.tag }}
          path: goloop

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build gochain-image
        run: make gochain-image
        working-directory: goloop

      - name: Push gochain-image to ghcr
        run: docker tag goloop/gochain:latest ghcr.io/${{ github.actor }}/drogon:latest
        working-directory: goloop
