name: Build and publish the gochain image

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
env:
 GOLOOP_VERSION: v1.3.3

jobs:
  build-goloop-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Clone goloop repository
        run: git clone https://github.com/icon-project/goloop.git
      
      - name: Checkout the release version
        run: git checkout ${{ env.GOLOOP_VERSION }}
        working-directory: goloop

      - name: Log in to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build gochain-image
        run: make gochain-image
        working-directory: goloop

      - name: Push gochain-image to docker hub
        run: |
          docker tag goloop/gochain:latest iconcommunity/gochain:latest
          docker push iconcommunity/gochain:latest
        working-directory: goloop